[package]
name = "chip8_rs"
version = "0.1.0"
authors = ["Mathijs Saey <mathijs@mathsaey.be>"]
edition = "2018"
description = "A Chip-8 emulator to dip my toes in Emulation & Rust"

[dependencies]
num = "0.2.1"
minifb = "0.15.3"
