[package]
name = "memu"
version = "0.1.0"
authors = ["Mathijs Saey <mathijs@mathsaey.be>"]
edition = "2018"
description = "Toy emulators written in Rust"

[dependencies]
num = "0.2.1"
minifb = "0.15.3"
